name: Bug report
description: Create a report to help us improve
title: "[BUG] <description>"
labels: [bug]
body:
  - type: textarea
    id: bugdescription
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Verify
        2. Complete
        3. Run tests
        4. Approve
        5. Merge
    validations:
      required: true
  - type: textarea
    id: expectedbhv
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
